### PR TITLE
changes i2c pins for miko_keyboard

### PR DESCRIPTION
**Pull request by michalkalinowski-**

### CODE REVIEW

**Comment by michalkalinowski-** [comment]
Sorry, I meant to open this PR agains my own fork. Closing this one.

**Comment by Gadgetoid** [comment]
:eyes: 

Ooooh! Whatcha workin' on? :laughing:

**Comment by michalkalinowski-** [comment]
IMG_1178
 
;)

Thanks for your awesome work on those libraries!

**Comment by Gadgetoid** [comment]
Niiiiiciiiiceee!

**Pull request closed without merging**
