### PR TITLE
Allow specifying a background color for image_converter

### PR DESCRIPTION
**Pull request by North101**
Add a `--bg` option to `image_converter.py` with the choices `black` or `white`. This is useful for converting images with transparency.

### CODE REVIEW

**Comment by North101** [comment]
Woops just realized it formatted on save. I'll redo the commit without that

**Comment by Gadgetoid** [comment]
Thank you!

Could you rebase this on main, please? A new version of flake8 broke our Python linting and this is stopping me from merging.

**Comment by North101** [comment]
> Thank you!
> 
> Could you rebase this on main, please? A new version of flake8 broke our Python linting and this is stopping me from merging.

Done. I was wondering if it should default to white. Currently `img.convert("1")` converts transparency to black

**Comment by Gadgetoid** [comment]
White might be a sensible default if you're willing and able to make the tweak.

Sorry for the delay getting back, I have been _stacked!_

**Comment by Gadgetoid** [comment]
The new and shiny Badger 2040 W library has been backported to Badger 2040 and moved here- https://github.com/pimoroni/badger2040

Both now have JPEG support, so converting bin files is ancient history and this converter will probably either get deleted, or expanded to support all PicoGraphics pen types and rehosted somewhere.

Either way, I'm closing this PR since all Badger python stuff is going to be removed from "pimoroni-pico"

And- once again- thank you!

**Comment by North101** [comment]
No worries, I agree that theres no point merging this.

**Pull request closed without merging**
