### PR TITLE
ST7789: Create generic display driver

### PR DESCRIPTION
**Pull request by Gadgetoid**
This change introduces an "ST7789" class to C++ and MicroPython. It allows the user to supply supply a width, height and rotation instead of the current ugliness of supplying a properly sized `bytearray()`. It would also combine all of the (ST7789-based) display product libraries into a single library so we don't have duplicated functionality all over the place (getting progressively worse with every new display product :grimacing:)

## TODO

1. [x] Bind ST7789 library + PicoGraphics to MicroPython
2. [x] Add support for various display orientations to ST7789
3. [x] Migrate PicoDisplay, and PicoDisplay 2" and all other ST7789-based devices to the generic ST7789
4. [ ] ~~Add shim modules (written in Python and baked into the firmware) to fake the old PicoDisplay and PicoDisplay2 module functionality~~
5. [x] Update the examples
6. [x] Remove Pico Display modules
7. [ ] Communicate The Old Way as deprecated (update documentation?)

### Phase 1 tests:

Test builds - https://github.com/pimoroni/pimoroni-pico/actions/runs/2017564653

1. [x] Pico Display
2. [x] Pico Display 2.0
3. [x] Pico Explorer

## Impact

This would change:

```python
import picodisplay as display

width = display.get_width()
height = display.get_height()

display_buffer = bytearray(width * height * 2)
display.init(display_buffer)
```

Into something a little more like:

```python
import st7789

WIDTH = 320
HEIGHT = 240

display = st7789.ST7789(WIDTH, HEIGHT, rotate180=False, slot=BG_SPI_FRONT)
```

It might involve breaking changes to the C++ API/SDK.

### CODE REVIEW

**Comment by alphanumeric007** [comment]
Portrait mode on Pico Display Pack 2 currently isn't working with the new Unifying driver. 
Landscape is fine but portrait is all garbled etc.
Both modes are fine on the Smaller Display pack though.

**Comment by Gadgetoid** [comment]
What on earth is `BG_SPI_FRONT` and where is it defined? :laughing:

**Comment by alphanumeric007** [comment]
There is a BG_SPI_CS_FRONT in the ST7789  _init_.py file. It sets the SPI CE pin
BG_SPI_CS_BACK = 0
BG_SPI_CS_FRONT = 1

I'm guessing that it defines The SPI DC pin, CE pin, and Backlight pin used by that BG Socket?

**Comment by Gadgetoid** [comment]
Okay I've just pushed an update that fixes rotations on Pico Display and Pico Display 2.0.

I don't really like how this all works, but it's the easiest way to reason about if you treat a portrait display as being native 240x320 from the start rather than 320x240 rotated 90 degrees.

There's a new parameter for the Python wrapper: `rotate180`. This does what you might expect.

If you want to use portrait mode on either display then supply the width/height swapped.

If you want to flip the display upside-down from either portrait or landscape mode then set `rotate180=True`.

Eg:

```python
# Pico Display portrait normal:
display = st7789.ST7789(135, 240, rotate180=False, slot=0)
# Pico Display portrait upside-down:
display = st7789.ST7789(135, 240, rotate180=True, slot=0)
```

I need to get those "slot" constants defined somewhere because that's all very confusing.

**Comment by Gadgetoid** [comment]
As a note to myself more than anyone else: I can't be fussed with shimming PicoDisplay and PicoDisplay2 functionality back in with a compatibility layer. If users want to upgrade to the latest and greatest "Pimoroni MicroPython" then they will need to migrate their application. We should provide a brief guide for this:

1. Swap PicoDisplay/PicoDisplay2 with ST7789 setup
2. Use `pimoroni.Button()` or PicoZero for Button input
3. Use `pimoroni.RGBLED()` for RGB LED control

**Comment by alphanumeric007** [comment]
Are these the ones I want to download?
https://github.com/pimoroni/pimoroni-pico/actions/runs/2017564653

I now have a second Display Pack v2 to play with. Will try to give this a go over the weekend. Messed up my back big time, and only just getting back normal. Still need to take it easy so it may be a few days before I tinker with any Pi or PICO stuff.

**Comment by Gadgetoid** [comment]
This one now - https://github.com/pimoroni/pimoroni-pico/actions/runs/2313202192

**Comment by alphanumeric007** [comment]
Great, thankyou, downloading as I type this.

**Comment by Gadgetoid** [comment]
Just did a very large refactor and also fixed a silly bug in ST7789 where it did not hold a reference to the framebuffer it allocated for itself... whoops... that caused some... things... to... happen.

**Comment by alphanumeric007** [comment]
Re download for the fixes?

**Comment by Gadgetoid** [comment]
This one now! :laughing: https://github.com/pimoroni/pimoroni-pico/actions/runs/2315167736

**Comment by alphanumeric007** [comment]
Thanks again Phil. your time and effort is very much appreciated. =)

**Comment by alphanumeric007** [comment]
Currently running two Display Pack V2's side by side in portrait mode without issue. And have access to the full 320 height and 240 width. woot =)
I don't have the buttons or LED's wired up on this setup just yet. 
The Display Packs are each mounted to Perma Proto half size, and the Pico to another Perma Proto half size. I just soldered male header on the Perma Proto's and then soldered wires from board to board for SPI and power. 

A big big thankyou Phil. A big thumbs up. 
My test file is as follows.
```
import time

import st7789
frame_buffer = bytearray(240 * 320 * 2)  # 2-bytes per pixel (RGB565)
display1 = st7789.ST7789(width=240, height=320, buffer=frame_buffer, slot=0) 
display2 = st7789.ST7789(width=240, height=320, buffer=frame_buffer, slot=1) 
display1.set_backlight(1.0)
display2.set_backlight(1.0)

print(display1)
print(display2)

while True:
    display1.set_pen(0, 0, 255)
    display1.clear()
    display1.update()
    display1.set_pen(0, 0, 0)  # Set pen to black
    display1.text("display 1", 10, 10, 240, 5)  
    display1.update()
    display1.clear()
    
    display2.set_pen(0, 255, 0)
    display2.clear()
    display2.update()
    display2.set_pen(0, 0, 0)  # Set pen to black
    display2.text("display 2", 10, 10, 240, 5)  
    display2.update()
    display2.clear()
    
    time.sleep(2)
    
    display1.set_pen(0, 255, 0)
    display1.clear()
    display1.update()
    display1.set_pen(0, 0, 0)  # Set pen to black
    display1.text("display 1 slot 0", 10, 10, 240, 5)  
    display1.update()
    display1.clear()
    
    display2.set_pen(0, 255, 255)
    display2.clear()
    display2.update()
    display2.set_pen(0, 0, 0)  # Set pen to black
    display2.text("display 2 slot 1", 10, 10, 240, 5)  
    display2.update()
    display2.clear()
    
    time.sleep(2)
    
    display1.set_pen(0, 255, 255)
    display1.clear()
    display1.update()
    display1.set_pen(0, 0, 0)  # Set pen to black
    display1.text("display 1 slot 0 BG_front", 10, 10, 240, 5)  
    display1.update()
    display1.clear()
    
    display2.set_pen(255, 0, 0)
    display2.clear()
    display2.update()
    display2.set_pen(0, 0, 0)  # Set pen to black
    display2.text("display 2 slot 1 BG_back", 10, 10, 240, 5)  
    display2.update()
    display2.clear()
    
    time.sleep(2)
    
    display1.set_pen(255, 0, 0)
    display1.clear()
    display1.update()
    display1.set_pen(0, 0, 0)  # Set pen to black
    display1.text("display 1 slot 0 BG_front cs=(17)", 10, 10, 240, 5) 
    display1.update()
    display1.clear()
    
    display2.set_pen(255, 0, 255)
    display2.clear()
    display2.update()
    display2.set_pen(0, 0, 0)  # Set pen to black
    display2.text("display 2 slot 1 BG_back cs=(22)", 10, 10, 240, 5) 
    display2.update()
    display2.clear()
    
    time.sleep(2)
    
    display1.set_pen(255, 0, 255)
    display1.clear()
    display1.update()
    display1.set_pen(0, 0, 0)  # Set pen to black
    display1.text("display 1 slot 0 BG_front cs=(17) bl=(20)", 10, 10, 240, 5) 
    display1.update()
    display1.clear()
    
    display2.set_pen(255, 255, 0)
    display2.clear()
    display2.update()
    display2.set_pen(0, 0, 0)  # Set pen to black
    display2.text("display 2 slot 1 BG_back cs=(22) bl=(21)", 10, 10, 240, 5)
    display2.update()
    display2.clear()
    
    time.sleep(2)
    
    display1.set_pen(255, 255, 0)
    display1.clear()
    display1.update()
    display1.set_pen(0, 0, 0)  # Set pen to black
    display1.text("display 1 slot 0 BG_front cs=(17) bl=(20) st7789", 10, 10, 240, 5)  
    display1.update()
    display1.clear()
    
    display2.set_pen(0, 0, 255)
    display2.clear()
    display2.update()
    display2.set_pen(0, 0, 0)  # Set pen to black
    display2.text("display 2 slot 1 BG_back cs=(22) bl=(21) st7789", 10, 10, 240, 5) 
    display2.update()
    display2.clear()
    
    time.sleep(2)
    
    display1.set_pen(255, 255, 0)
    display1.clear()
    display1.update()
    display1.set_pen(0, 0, 0)  # Set pen to black
    display1.text("display 1 slot 0 BG_front cs=(17) bl=(20) st7789 240 x 320", 10, 10, 240, 5)  
    display1.update()
    display1.clear()
    
    display2.set_pen(0, 0, 255)
    display2.clear()
    display2.update()
    display2.set_pen(0, 0, 0)  # Set pen to black
    display2.text("display 2 slot 1 BG_back cs=(22) bl=(21) st7789 240 x 320", 10, 10, 240, 5) 
    display2.update()
    display2.clear()
    
    time.sleep(2)
    
    display1.set_pen(255, 255, 0)
    display1.clear()
    display1.update()
    display1.set_pen(0, 0, 0)  # Set pen to black
    display1.text("display 1 slot 0 BG_front cs=(17) bl=(20) st7789 240 x 320 portrait", 10, 10, 240, 5)  
    display1.update()
    display1.clear()
    
    display2.set_pen(0, 0, 255)
    display2.clear()
    display2.update()
    display2.set_pen(0, 0, 0)  # Set pen to black
    display2.text("display 2 slot 1 BG_back cs=(22) bl=(21) st7789 240 x 320 portrait", 10, 10, 240, 5) 
    display2.update()
    display2.clear()
    
    time.sleep(2)    
```

**Pull request merged**
