### PR TITLE
added midpt-ellipse

### PR DESCRIPTION
**Pull request by Toastee0**
Draws elipses. midptellipse(int x radius, int y radius, Point)
Re-try, after clean rebase.

### CODE REVIEW

**Comment by Gadgetoid** [comment]
I think this will explode since all surface manipulation must now go via `set_pixel` for a single pixel or `set_pixel_span` for a horizontal span. The actual framebuffer is now `void *` and isn't guaranteed to be in any particular format or layout.

**Comment by Toastee0** [comment]
I'll rewrite it using set pixel, and a check bounds function.

**Comment by Gadgetoid** [comment]
This has been languishing for a while, any interest in bringing it kicking and screaming into 2023 PicoGraphics?

**Comment by Gadgetoid** [comment]
Note to self that adding Ellipse to #783 might be a good idea.

Closing this for now, feel free to re-open if you decide to tackle it!

**Pull request closed without merging**
