### PR TITLE
Create Balls_Demo.py

### PR DESCRIPTION
**Pull request by dsssssssss9**
have adapted the demo.py in the pico_display examples to run full screen on the Pico Explorer built-in display.

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Thank you! If you've got a moment to re-apply this to the updated bouncy boundary boxed balls from #69 and update your PR that'd be great. Also "Balls_Demo.py" should be "balls_demo.py".

(And while I would normally use `-` in lieu of `_` I've heard that MicroPython users like to save various demo code on their device and run it with - for example - `import balls_demo` so underscore is right.)

**Comment by dsssssssss9** [comment]
Hi 
please excuse me asking as this is my first ever PR!!

how do i update my PR  with the new code please?

**Comment by dsssssssss9** [comment]
i hope this was the correct way to do it?

**Comment by dsssssssss9** [comment]
Hi
realise you are probably very very busy at the moment but could you let me know if this PR meets your requirements - its my first ever & I'm keen to see if i have done this correctly

**Comment by Gadgetoid** [comment]
Sorry for the lack of feedback- we really have been super busy!

Git-Fu required to correctly update a pull request can be decidedly complicated, but your goal is to get this change to a single commit that adds `balls_demo.py` into the relevant location. You can opt to close this PR and raise a new one with the one-file-one-commit, or you can delve into some Git-Fu.

Your `Create balls_demo.py` commit is pretty good, here's the link to the patch: https://github.com/pimoroni/pimoroni-pico/commit/0f98207c4774808c728e4656a31fb09942a2de43.patch

It's adding the file to the wrong location, though so let's create a new patch branch locally and fix that.

In your local copy of your fork, add upstream as a new remote so you can fetch the latest changes:

```
git remote add upstream git://github.com/pimoroni/pimoroni-pico.git
```

Fetch the contents of main from "upstream":

```
git fetch upstream main
```

Create a clean new branch for your commit, based upon `upstream/main`:

```
git checkout patch-balls-demo upstream/main
```

"Cherry-pick" your desired commit from your old `patch-1` branch (assuming you have fetched it locally):

```
git cherry-pick 0f98207c4774808c728e4656a31fb09942a2de43
```

That long string "0f98207c4774808c728e4656a31fb09942a2de43" is the commit hash, you'll notice it matches the URL above, it's a unique identifier for your change that will allow you to pull it across from your `patch-1` branch into our new `patch-balls-demo` branch.

Move `balls_demo.py` into its new home:

```
mv balls_demo.py micropython/examples/pico_explorer/
```

Make sure git knows you've moved the file by adding the old and new locations:

```
git add balls_demo.py
git add micropython/examples/pico_explorer/balls_demo.py
```

*Amend* your  commit with this new change:

```
git commit --amend
Ctrl + X
```

Voila! 

You can inspect the last commit and see how it differs from the previous one to verify this:

```
git diff HEAD~1 | head -n 5
diff --git a/micropython/examples/pico_explorer/balls_demo.py b/micropython/examples/pico_explorer/balls_demo.py
new file mode 100644
index 0000000..8497d15
--- /dev/null
+++ b/micropython/examples/pico_explorer/balls_demo.py
```

Finally you can push the branch up and raise an new PR with it... heck you can even delete your local `patch-1` re-created it from `patch-balls-demo` and *force push* it to rewrite history and update your PR. Force pushes are generally accepted practise for patches and changes, since you want a clean history to join upstream.

Of course you can do all of the above just by copying and pasting the file around and adding it as a new commit... but Git Fu is fun!

**Pull request closed without merging**
