### PR TITLE
ST7789 / PicoGraphics rewrite - Support for 4-bit, 8-bit and 16-bit framebuffers and more.

### PR DESCRIPTION
**Pull request by Gadgetoid**
:information_source: Latest test builds - https://github.com/pimoroni/pimoroni-pico/actions/runs/2514970828 (now with MicroPython v1.19, PIO accelerated ST7789 parallel output, performance tweaks, Tufty2040 build, updated 17 Jun, 11:00 GMT)

A 340x240 16-bit framebuffer uses a whopping 150k of RAM. This is relatively okay in C++ but causes issues in MicroPython where the gc_heap is *only* 192k.

This set of changes allow you to use a native 16-bit, smaller 8-bit, or *tiny* 4-bit framebuffer for most of our SPI displays. This lets you balance memory usage with available colours and display performance.

This change renames the `st7789` module to `picographics` in MicroPython.

### Bringup

Here's an example bringup for the 160x80 ST7735 LCD in true-colour RGB565 mode:

```python
from picographics import PicoGraphics, DISPLAY_LCD_160X80, PEN_RGB565

display = PicoGraphics(display=DISPLAY_LCD_160X80, pen_type=PEN_RGB565)
```

The above uses 25K of RAM and supports 65K colours.

```python
from picographics import PicoGraphics, DISPLAY_LCD_160X80, PEN_P4

display = PicoGraphics(display=DISPLAY_LCD_160X80, pen_type=PEN_P4)
```

The above uses 6.25K of RAM and supports 8 colours!

### Custom Pins

You can use your own pins for supported SPI or Parallel displays.

You must construct an SPIBus or ParallelBus object using the `pimoroni_bus` module:

```python
from pimoroni_bus import SPIBus
from picographics import PicoGraphics, DISPLAY_PICO_EXPLORER, PEN_RGB332

spibus = SPIBus(cs=17, dc=16, sck=18, mosi=19)

display = PicoGraphics(display=DISPLAY_PICO_EXPLORER, bus=spibus, pen_type=PEN_RGB332)
```

### Saving More RAM / Doing Weird Things

If you need to temporarily claim back RAM from PicoDisplay, or use multiple framebuffers, you can use `set_framebuffer` to set/clear the region of memory it uses internally.

:warning: *DO NOT* attempt to draw when no framebuffer is set. You'll have a bad time!

```python
from picographics import PicoGraphics, get_buffer_size, DISPLAY_LCD_160X80, PEN_P4

# Big enough for 160 * 80 at 4-bits per pixel
buf = bytearray(get_buffer_size(DISPLAY_LCD_160X80, PEN_P4))

display = PicoGraphics(display=DISPLAY_LCD_160X80, pen_type=PEN_P4,  buffer=buf)

# Detach the framebuffer from PicoGraphics
display.set_framebuffer(None)

# Set a different framebuffer
buf2 = bytearray(int(160 * 80 / 2))
display.set_framebuffer(buf2)
```

### Displaying JPEG files

Thanks to JPEGDEC - https://github.com/bitbank2/JPEGDEC - you can load and display JPEG files via PicoGraphics, like so:

```python
import picographics
import jpegdec

lcd = picographics.PicoGraphics(display=picographics.DISPLAY_PICO_EXPLORER, rotate=0, pen_type=picographics.PEN_RGB565)

# Create a new JPEG decoder for our PicoGraphics
j = jpegdec.JPEG(lcd)

# Open the JPEG file
j.open_file("240.jpeg")

# Decode the JPEG
j.decode(0, 0, 0)

# Display the result
lcd.update()
```

The arguments to "decode" are x-offset, y-offset and scale. Value scale values are:

```python
JPEG_SCALE_HALF = 2
JPEG_SCALE_QUARTER = 4
JPEG_SCALE_EIGHTH = 8
```

When you call `decode` the jpeg decoder makes a best effort to draw into your PicoGraphics surface in a sensible pixel format.

### Sprites

Pico Graphics has very basic support for 128x128 spritesheets in PEN_RGB332 mode:

```python
from picographics import PicoGraphics, DISPLAY_TUFTY_2040, PEN_RGB332
import time

lcd = PicoGraphics(DISPLAY_TUFTY_2040, pen_type=PEN_RGB332)

# Reserve a large enough buffer
sprites = bytearray(128 * 128)

# Load a spritesheet into the buffer
open("s4m_ur4i-dingbads.rgb332", "rb").readinto(sprites)
#open("s4m_ur4i-pirate-characters.rgb332", "rb").readinto(sprites)

# Tell PicoGraphics to use this new spritesheet
lcd.set_spritesheet(sprites)

# Draw a sprite
lcd.sprite(0, 0, 10, 10, 255)
 ```

The function `sprite` takes:

* the X/Y index of a sprite in the spritesheet. These should be between 0-15.
* the X/Y coordinates to draw the sprite on screen.
* the colour to treat as transparent

### Supported Displays

The current list of supported displays is:

* `DISPLAY_ENVIRO_PLUS`
* `DISPLAY_LCD_160X80`
* `DISPLAY_LCD_240X240`
* `DISPLAY_PICO_DISPLAY`
* `DISPLAY_PICO_DISPLAY_2`
* `DISPLAY_PICO_EXPLORER`
* `DISPLAY_ROUND_LCD_240X240`
* `DISPLAY_TUFTY_2040`

### Supported Pen Types

* `PEN_P4` - 4-bit packed, with an 8 colour palette. This is commonly used for 7/8-colour e-ink displays or driving large displays with few colours.
* `PEN_P8` - 8-bit, with a 256 colour palette. Great balance of memory usage versus available colours. You can replace palette entries on the fly.
* `PEN_RGB332` - 8-bit, with a fixed 256 colour RGB332 palette. Great for quickly porting an RGB565 app to use less RAM. Limits your colour choices, but is easier to grok.
* `PEN_RGB565` - 16-bit, 65K "True Colour." Great for rainbows, gradients and images but comes at the cost of RAM!

# TODO

* [ ] Add some new documentation here!
* [x] Handle a failure to allocate a palette colour (return -1 if we've run out of palette space?)
* [x] Provide MicroPython bindings for palette put/get methods
* [x] Provide a way to initialize a specific display type's args automatically, eg: `ST7789(display=SPI_LCD_240X240)`
* [x] Update all examples to remove `set_pen(r, g, b)` since this is meaningless and deprecated
* [ ] Write a migration guide
* [ ] Update documentation
* [x] Remove obsolete functions from Pico Display & Pico Explorer classes- should be header-only defines of pins
* [ ] Create a C++ "Buzzer" driver to mirror the MicroPython one and replace "pico_explorer.set_tone()"

# TO TEST

* [x] Pico Display 2.0 - All rotations
* [x] Pico Display - All rotations
* [x] SPI LCD 240 x 240 - All rotations
* [x] Pico Explorer - All rotations

### CODE REVIEW

**Comment by Gadgetoid** [comment]
@alphanumeric007 this may be relevant to your interests!

**Comment by alphanumeric007** [comment]
Yes, that may be a big advantage for me. I pretty well stick to the basic colors. Red, Yellow, Green, and Blue. And on occasion Orange and Violet. I have a PICO Breakout Garden Base, and a couple of the 1.5" st7789 LCD Breakouts I can use for testing if that helps?

**Comment by Gadgetoid** [comment]
No great need to test in depth, but it should get you back about 75K of RAM in your dual display setup. Or let you have separate framebuffers if you really want!

Your limited use of colour should make it pretty much a drop-in replacement and you wont notice much. To use your specified colours you can trash the default palette:

```
st7789.flush_palette()
```

And specify not to truncate new colours to RGB332 on creation:

```
st7789.create_pen(255, 0, 255, truncate=False)
```

Or create all your colours up-front, which returns an 0-255 palette index:

```
GREEN = st7789.create_pen(0, 255, 0, truncate=False)
st7789.set_pen(GREEN)
```

I might actually force this behavior at the expense of upsetting a few people who've used  `set_pen(r, g, b)` since it will make those function calls a little faster.

I hate breaking compatibility with user code, but we've got some bad design choices to fix!

**Comment by Doukakis** [comment]
Nice idea! It makes the above board far more useful in MicroPython.

**Comment by Doukakis** [comment]
You can also add a way to detach and free the FB temporarily. Since the display contains its own RAM, if we TEMPORARILY need lots of RAM (eg. to load an image to prepare a printout to a thermal printer, calculate a QR code) it would be of great help to do the following:
a) Free the framebuffer + garbage collect (gain 75K of RAM)
b) The previous display image remains on the LCD, backed-up by the controller RAM
c) Do the calculations that need RAM - cannot display anything at that point
d) Free memory, garbage collect, re-create Framebuffer and continue.
e) We just have to repaint the full frame

**Comment by Doukakis** [comment]
Thanks a lot!

**Comment by Gadgetoid** [comment]
Done as described above. Don't uh... try to draw while the framebuffer is unset :laughing: the library will not check.

**Comment by alphanumeric007** [comment]
Thanks Phil =), very much appreciated. I will tinker with this over the weekend. Just poured myself a grog of Captain Morgan's Dark Rum. It's the Pirate thing to do on a Friday evening. ;)

**Comment by Gadgetoid** [comment]
I've updated the Pico Display Python examples to demonstrate some of the changes.

To use custom colours:

```python
display.set_palette_mode(st7789.PALETTE_USER)
BLACK = display.create_pen(0, 0, 0)
CUSTOM = BLACK + 1
display.set_palette(CUSTOM, 255, 0, 255) # Set the CUSTOM entry to RED
display.set_pen(CUSTOM)
```

To easy init a display:

```python
display = st7789.ST7789(st7789.DISPLAY_PICO_DISPLAY, rotate=0)
```

I am trying to support all rotations, but getting the settings right is tricky :laughing:  much testomg and tweaking to do.

**Comment by alphanumeric007** [comment]
One wrinkle for me is I have display1 and display2. 
frame_buffer = bytearray(240 * 320 * 2)
display1 = st7789.ST7789(width=240, height=320, buffer=frame_buffer, slot=0)
display2 = st7789.ST7789(width=240, height=320, buffer=frame_buffer, slot=1)

So I'll have to do something like the following.
BLACK1 = display1.create_pen(0, 0, 0)
BLACK2= display2.create_pen(0, 0, 0)

BLACK = display.create_pen(0, 0, 0)
display1.set_pen(BLACK)
gets me a display not defined error. Which was why I went with
display1.set_pen(0, 0, 0)

**Comment by Gadgetoid** [comment]
@alphanumeric007 in the default RGB332 any colour you create on one display will be the same on the other, so you can create them once and use them on both. Internally it just crushes that colour to its RGB332 representation, then looks up and returns its index into the palette.

**Comment by Gadgetoid** [comment]
Latest build, slot param - and most others - have gone.

All SPI or Parallel pins must be supplied as a "pimoroni_bus". This has a helper factory to create pins for slots, see below:

```python
BUF = bytearray(320 * 240)

BUS_BG_FRONT = pimoroni_bus.SPISlot(0)
BUS_BG_BACK = pimoroni_bus.SPISlot(1)

display = st7789.ST7789(st7789.DISPLAY_PICO_DISPLAY_2, rotate=90, buf=BUF, bus=BUS_BG_FRONT)
display = st7789.ST7789(st7789.DISPLAY_PICO_DISPLAY_2, rotate=90, buf=BUF, bus=BUS_BG_BACK)
```

`rotate` is intended to work properly on all displays, but probably doesn't yet. This replaces flipping the WIDTH/HEIGHT (which you no longer supply) and also the `rotate180` nonsense.

To get the WIDTH/HEIGHT of a display - for portable code - use:

```python
WIDTH, HEIGHT = display.get_bounds()
```

I've finally arrived at something I'm more or less happy with for the Python API. Hopefully it wont change much from here. Albeit there are certainly some considerable DMA performance gains to be had for the palette-based display refresh.

My sinuses are screaming at me to stick a steam train up each nostril. Will clean this up for release this coming week.

**Comment by alphanumeric007** [comment]
Ok, so how do I create the color once, and use it on both displays, code wise? Looks up at very dark light bulb hovering over head.

**Comment by Gadgetoid** [comment]
@alphanumeric007 for `USER` palettes I think you'd need a wrapper function to create the same colour on each display.

```python3
def create_pen(r, g, b):
    display1.create_pen(r, g, b)
    return display2.create_pen(r, g, b)
```

There's no reason why the palettes shouldn't stay completely in sync.

For `RGB323` palette mode `display1.create_pen(r, g, b)` will always return the same index as `display2.create_pen(r, g, b)` even when called out of order. The colours are fixed and you're just getting an index into the fix palette.

It stuck me last night that you can just draw into *one* display since they share the same back buffer, but calling `display2.update()` would still use the palette from display2.

**Comment by alphanumeric007** [comment]
I just now figured it out. Well one way to do it anyway. This is with the stock framebuffer, not the new 8 bit one.
I changed all my instances of display1, to just display. 
white = display.create_pen(255, 255, 255)
display.set_pen(white) <<worked
display2.set_pen(white) << also worked. =)

**Comment by Gadgetoid** [comment]
Ah with the stock framebuffer `create_pen()` always returns a packed 16-bit colour value, so it's always the same on any display.

Internally it just does:

```c++
uint16_t p = ((r & 0b11111000) << 8) |
             ((g & 0b11111100) << 3) |
             ((b & 0b11111000) >> 3);

return __builtin_bswap16(p);
```

Whereas the new 8-bit stuff - by default (in RGB332 mode) - does:

```c++
return (r & 0b11100000) | ((g & 0b11100000) >> 3) | ((b & 0b11000000) >> 6)
```

Either way a created pen is transferable, the only differences is how many bits of colour information are thrown away.

**Comment by alphanumeric007** [comment]
I wasn't using create_pen at all in my current code. I was doing the (255, 255, 255) thing. 
I figured I'd get that working with dual displays first, with the current uf2 file.
Then try your new 8bit buffer uf2. If I then have issues it should be easier to figure out what's "now" not working. ;)

**Comment by alphanumeric007** [comment]
Just flashed the new uf2 to that Pico.
This works > display = st7789.ST7789(st7789.DISPLAY_PICO_DISPLAY_2, rotate=90)
But this doesn't > display = st7789.ST7789(st7789.DISPLAY_PICO_DISPLAY_2, rotate=90, buf=BUF, bus=BUS_BG_FRONT)
TypeError: extra keyword arguments given

I added / edited to this
import st7789
import pimoroni_bus

BUF = bytearray(320 * 240)

BUS_BG_FRONT = pimoroni_bus.SPISlot(0)
BUS_BG_BACK = pimoroni_bus.SPISlot(1)

display = st7789.ST7789(st7789.DISPLAY_PICO_DISPLAY_2, rotate=90, buf=BUF, bus=BUS_BG_FRONT)
display2 = st7789.ST7789(st7789.DISPLAY_PICO_DISPLAY_2, rotate=90, buf=BUF, bus=BUS_BG_BACK)

**Comment by alphanumeric007** [comment]
Ah, OK, that fixed it. Working now with that latest 8bit test uf2 file. Next step is to do the 8-bit edits etc. 
I'm using your latest test file, but with a normal buffer size. 

BUF = bytearray(240 * 320)

BUS_BG_FRONT = pimoroni_bus.SPISlot(0)
BUS_BG_BACK = pimoroni_bus.SPISlot(1)

display = st7789.ST7789(st7789.DISPLAY_PICO_DISPLAY_2, rotate=270, buffer=BUF, bus=BUS_BG_FRONT)
display2 = st7789.ST7789(st7789.DISPLAY_PICO_DISPLAY_2, rotate=270, buffer=BUF, bus=BUS_BG_BACK)

**Comment by alphanumeric007** [comment]
I hate to be a pest, but I'm a bit lost with all the different bits of code posted above?
Not sure what bits to use?

**Comment by Gadgetoid** [comment]
A first port of cal would be to replace any instance of:

```python
display.set_pen(r, g, b)
```

With a:

```python
COLOR = display.create_pen(r, g, b)
display.set_pen(COLOR)
```

Then give all your colours sensible names and move their creation up to the top of the file after display init.

You can also just opt for the easy way and do:

```python
display.set_pen(display.create_pen(r, g, b))
```

**Comment by alphanumeric007** [comment]
That's all already done Phil.  Once I got the one color (white) working I modified all my other code for custom colors.
white = display.create_pen(255, 255, 255)
black = display.create_pen(0, 0, 0)
red = display.create_pen(255, 0, 0)
green = display.create_pen(0, 255, 0)
blue = display.create_pen(0, 0, 255)
yellow = display.create_pen(255, 255, 0)
orange = display.create_pen(255, 140, 0)
grey = display.create_pen(120, 120, 120)
violet = display.create_pen(255, 0, 255)

**Comment by Gadgetoid** [comment]
Oh nice!

How's it coming together? Is there anything you're stuck on?

I think I mostly need to fix rotation on the circular display before I can merge this and release another official pre-release.

I've gone deep down a rabbit hole of breaking things and scrutinizing our codebase though :laughing:

**Comment by alphanumeric007** [comment]
It's coming along good. Right now I'm using the full buffer, not the 8 bit.  So I'm thinking I need use "RGB332" Mode or "USER" Mode?
You have made a bunch of updates since this started so I'm not sure what may have changed or how to set it to 8 bit.

**Comment by alphanumeric007** [comment]
nBytes = gc.mem_free() is saying I have 98208 bytes free. That's up ~70 kb from what I had before. So I guess I'm already there?

**Comment by Gadgetoid** [comment]
> nBytes = gc.mem_free() is saying I have 98208 bytes free. That's up ~70 kb from what I had before. So I guess I'm already there?

Yup! You're there.

Sorry for the radio silence- sinus infection totally floored me for a few days.

**Comment by alphanumeric007** [comment]
I know what its like to be MIA. I have back issues and sciatica. The sciatica is a literal pain in the but that makes sitting in a chair for any length of time painful. When my back is at its worst I'm horizontal in bed for days on end. Just my XBOX for internet stuff. The onboard keyboard is frustrating to use so I don't post much from the XBOX.

Anyway, yeah, I figured out I was good to go. Just have to find my getup and go, lol.

**Comment by Gadgetoid** [comment]
Well instead of finishing the things on my TODO list we realised a unified graphics library that works for our UC8159 e-ink displays would be nice... so I now have a working 4-bit version of this with an 8-colour palette.

Uses about 38K RAM for a 320x240 display at the cost of only supporting 8 colours in any given update.

**Comment by Gadgetoid** [comment]
@alphanumeric007 I have unleashed horrible changes for you to catch up with :laughing: 

## Main Changes

Functions removed:
* `set_palette_mode` - obsolete, pen mode is now picked in constructor
* `set_palette` - now renamed `update_pen` which will replace a palette entry in P modes (bug: also does this in RGB332, do not rely on this)
* `reserve_palette` - obsolete, just use `create_pen()` to return a palette index, and `update_pen` to update that colour

The *BIG* change here is that `st7789` is *gone*. You must now:

```python
import picographics
display = picographics.PicoGraphics(display=picographics.DISPLAY_PICO_DISPLAY_2)
```

## Setting your buffer type (RAM usage vs available colours)

`PicoGraphic` has a new `pen_type` argument which accepts one of:

* `PEN_P4` - 4 bits per pixel mode, 8 colours, default palette loosely matches our 7-colour e-ink
* `PEN_P8` - 8 bits per pixel mode, 256 colours, empty palette
* `PEN_RGB332` - 8 bits per pixel mode, 256 colours, FIXED RGB332 palette. We might try to PIO accelerate this.
* `PEN_RGB565` - 16 bits per pixel mode, 65K colours (true colour)

P4 mode will use 320*240/2 bytes of RAM for Pico Display 2. That's about 38K. Handy if you want very few colours but tiny RAM usage.

P8 mode will use 320*240 bytes of RAM. That's 75K. Etc. etc.

The ST7735-based 160x80 LCD is now supported in PicoGraphics as `DISPLAY_LCD_160X80`.

## Known issues

* `set_framebuffer` is currently broken
* `PEN_RGB332` mode will currently let you replace palette colours, it probably shouldn't since if we PIO accelerate the conversion from RGB332 -> RGB565 the palette will be immutable.
* Functions like `update_pen` do not return an error when they are unsupported, they just don't work

**Comment by Gadgetoid** [comment]
Solarized palette in 8-colour mode:

```python
import picographics

lcd = picographics.PicoGraphics(display=picographics.DISPLAY_LCD_160X80, pen_type=picographics.PEN_P4)

# Some friendly names for our eight colour palette
BASE = 0
YELLOW = 1
RED = 2
MAGENTA = 3
VIOLET = 4
BLUE = 5
CYAN = 6
GREEN = 7

lcd.set_font("font8")

# Prime the palette with solarized dark!
lcd.set_palette([
    (0x00, 0x2b, 0x36),
    (0xb5, 0x89, 0x00),
    (0xdc, 0x32, 0x2f),
    (0xd3, 0x36, 0x82),
    (0x6c, 0x71, 0xc4),
    (0x26, 0x8b, 0xd2),
    (0x2a, 0xa1, 0x98),
    (0x85, 0x99, 0x00)
])

lcd.set_pen(BASE)
lcd.clear()

for pen in (1, 2, 3, 4, 5, 6, 7):
    lcd.set_pen(pen)
    lcd.text("Hello World - {}".format(pen), 0, pen * 11 - 11, 160)

lcd.update()
```

**Comment by Gadgetoid** [comment]
Added a `get_buffer_size` method so you can take the guesswork out of allocating a correctly-sized buffer:

```python3
from picographics import PicoGraphics, get_buffer_size, DISPLAY_PICO_DISPLAY_2, PEN_RGB565

buffer = bytearray(get_buffer_size(DISPLAY_PICO_DISPLAY_2, PEN_RGB565))
lcd = PicoGraphics(display=DISPLAY_PICO_DISPLAY_2, rotate=180, pen_type=PEN_RGB565, buffer=buffer)
```

**Comment by alphanumeric007** [comment]
Wow, your a busy man there Phil. I'll catch up at some point. Been busy with mundane chores like yardwork etc. =(

**Comment by alphanumeric007** [comment]
I can relate to what your up to. I usually start out with a "big" block or "working" code. Then at some point i want to add and or refine it. Then I have one of those "why did I do it that way moments?" Then do a change it, break it, fix it. Waash rinse and repeat. =)

**Comment by alphanumeric007** [comment]
Just about time to grab my Pico Breakout Garden and have a look see. 
I have a Display Pack V1 sitting here doing nothing at the moment too.

**Comment by alphanumeric007** [comment]
Confused as to how to setup dual displays?
Using the following I don't get any errors, but both displays are black / blank? I don't think the backlights are on?
```
from pimoroni_bus import SPIBus
from pimoroni_bus import ParallelBus
from picographics import PicoGraphics, DISPLAY_PICO_DISPLAY_2, PEN_RGB332
spibus = SPIBus(cs=22, dc=16, sck=18, mosi=19)
spibus2 = SPIBus(cs=17, dc=16, sck=18, mosi=19)

display = PicoGraphics(display=DISPLAY_PICO_DISPLAY_2, bus=spibus, pen_type=PEN_RGB332)
display2 = PicoGraphics(display=DISPLAY_PICO_DISPLAY_2, bus=spibus2, pen_type=PEN_RGB332)

display.set_backlight(1.0)
display2.set_backlight(1.0)
```

**Comment by alphanumeric007** [comment]
spibus = SPIBus(cs=22, dc=16, sck=18, mosi=19, bl=21 )
spibus2 = SPIBus(cs=17, dc=16, sck=18, mosi=19, bl=20)

Got the backlights working. =) 
Just have to figure out how to rotate the image?

**Comment by alphanumeric007** [comment]
My BME280 is now not working correctly? I get a reading, but it then just stays static and won't update. My BME680 is working just fine. I can pinch it with my fingers and watch the temp and humidity readings change. Nothing happens with the BME280.
My code and the micro python demo do the same thing. Stock address and 0x77. Even unplugged the BME680 while testing. It was working with an earlier official build. Not sure when it stopped working?

**Comment by Gadgetoid** [comment]
@alphanumeric007 I "fixed" it in this commit  - https://github.com/pimoroni/pimoroni-pico/commit/496c1a3b45a7bffab3d249e387d4c3e1653e2e4f - and this branch has since been rebased upon it.

The problem you describe is exactly what I was seeing when I fixed it. I am flummoxed!

**Comment by alphanumeric007** [comment]
I must have grabbed the wrong (work in progress) uf2 file. I'll go get the latest test build and see how it works.

**Comment by alphanumeric007** [comment]
BME280 working now Phil. My bad, grabbed the wrong uf2 file. . 
If I use PEN_P8 I only get one display. Just a FYI, that may be a limitation of that mode. RGB332 works just fine though. =)

**Comment by Gadgetoid** [comment]
Whew regarding the BME280!

> If I use PEN_P8 I only get one display. Just a FYI, that may be a limitation of that mode

That's odd. PEN_P8 and RGB332 should be the same size! I will look into it.

**Comment by Gadgetoid** [comment]
Well dontchaknow PEN_P8 was using a 16-bit pen size to calculate the buffer size. Fixed! Good spot, thank you!

**Comment by alphanumeric007** [comment]
PEN_P8 still not working for me? I may have my code messed up though?
The screen is split in two, and then the top half split it two again, with my text duplicated in the two top halves?

```
import time
import picographics
from pimoroni_bus import SPIBus


from picographics import PicoGraphics, get_buffer_size, DISPLAY_PICO_DISPLAY, PEN_P8
#from picographics import PicoGraphics, DISPLAY_PICO_DISPLAY, PEN_RGB332

buf = bytearray(get_buffer_size(DISPLAY_PICO_DISPLAY, PEN_P8))

display = PicoGraphics(display=DISPLAY_PICO_DISPLAY, rotate=270 ,pen_type=PEN_P8,  buffer=buf)
#display = PicoGraphics(display=DISPLAY_PICO_DISPLAY, rotate=270, pen_type=PEN_RGB332)

display.set_backlight(1.0)

black = display.create_pen(0, 0, 0)
red = display.create_pen(255, 0, 0)
green = display.create_pen(0, 255, 0)
blue = display.create_pen(0, 0, 255)

while True:
    display.set_pen(red)    # Set pen to a red
    display.clear()         # Fill the screen with the colour
    display.set_pen(black)  # Set pen to black
    #display.text("pico display pack", 10, 10, 240, 6)   # landscape
    display.text("pico display pack", 10, 10, 135, 3)    # potrait 
    display.update()        # Update the display
    time.sleep(1.0)
    
    display.set_pen(green)  # Set pen to a green
    display.clear()         # Fill the screen with the colour
    display.set_pen(black)  # Set pen to black
    #display.text("pico display pack", 10, 10, 240, 6)   # landscape
    display.text("pico display pack", 10, 10, 135, 3)    # potrait 
    display.update()        # Update the display
    time.sleep(1.0)
    
    display.set_pen(blue)   # Set pen to a blue
    display.clear()         # Fill the screen with the colour
    display.set_pen(black)  # Set pen to black
    #display.text("pico display pack", 10, 10, 240, 6)   # landscape
    display.text("pico display pack", 10, 10, 135, 3)    # potrait 
    display.update()        # Update the display
    time.sleep(1.0)    
```

**Comment by Gadgetoid** [comment]
Yup that's apparently very broken. Looking into it.

**Comment by alphanumeric007** [comment]
Working now Phil. =)
Is there any advantage to me, to use PEN_P8 over PEN_RGB332? In my dual display setup.

**Comment by alphanumeric007** [comment]
Haven't figured out how to get PEN_P4 mode to work?
MicroPython v1.18 on 2022-06-14; Raspberry Pi Pico with RP2040

Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 30, in <module>
ValueError: create_pen failed. No matching colour or space in palette!

```
import time
import picographics
from pimoroni_bus import SPIBus

from pimoroni import Button
button_a = Button(12)
button_b = Button(13)
button_x = Button(14)
button_y = Button(15)


from pimoroni import RGBLED
led = RGBLED(6, 7, 8)

from picographics import PicoGraphics, DISPLAY_PICO_DISPLAY, PEN_P4
#from picographics import PicoGraphics, DISPLAY_PICO_DISPLAY, PEN_P8
#from picographics import PicoGraphics, DISPLAY_PICO_DISPLAY, PEN_RGB332

#buf = bytearray(get_buffer_size(DISPLAY_PICO_DISPLAY, PEN_P4))
#buf = bytearray(get_buffer_size(DISPLAY_PICO_DISPLAY, PEN_P8))

display = PicoGraphics(display=DISPLAY_PICO_DISPLAY, rotate=270 ,pen_type=PEN_P4)
#display = PicoGraphics(display=DISPLAY_PICO_DISPLAY, rotate=270 ,pen_type=PEN_P8)
#display = PicoGraphics(display=DISPLAY_PICO_DISPLAY, rotate=270, pen_type=PEN_RGB332)

display.set_backlight(1.0)



black = display.create_pen(0, 0, 0)
red = display.create_pen(255, 0, 0)
green = display.create_pen(0, 255, 0)
blue = display.create_pen(0, 0, 255)

while True:
    display.set_pen(red)    # Set pen to a red
    display.clear()         # Fill the screen with the colour
    display.set_pen(black)  # Set pen to black
    #display.text("pico display pack", 10, 10, 240, 6)   # landscape
    display.text("pico display pack", 10, 10, 135, 3)    # potrait 
    display.update()        # Update the display
    led.set_rgb(255, 0, 0)
    time.sleep(1.0)
    
    display.set_pen(green)  # Set pen to a green
    display.clear()         # Fill the screen with the colour
    display.set_pen(black)  # Set pen to black
    #display.text("pico display pack", 10, 10, 240, 6)   # landscape
    display.text("pico display pack", 10, 10, 135, 3)    # potrait 
    display.update()        # Update the display
    led.set_rgb(0, 255, 0)
    time.sleep(1.0)
    
    display.set_pen(blue)   # Set pen to a blue
    display.clear()         # Fill the screen with the colour
    display.set_pen(black)  # Set pen to black
    #display.text("pico display pack", 10, 10, 240, 6)   # landscape
    display.text("pico display pack", 10, 10, 135, 3)    # potrait 
    display.update()        # Update the display
    led.set_rgb(0, 0, 255)
    time.sleep(1.0)    
```

**Comment by alphanumeric007** [comment]
PEN_P4 working now on my Pico Display single test setup. =) 
Next step is to try some of this on my dual Pico Display setup.

**Comment by alphanumeric007** [comment]
Something is broken in those latest test uf2 files? 
I'm getting "Unknown USB Device (Device Descriptor Request Failed)" and Thonny won't connect?
1.18.7 is fine, but 
pimoroni-picolipo_16mb-156ab5c6b4d5a12b3ae6458b53f171d59578bffb-micropython.uf2
and some of the previous versions have an issue.

**Comment by Gadgetoid** [comment]
For dual display you should use something like:

```python
from picographics import PicoGraphics, DISPLAY_PICO_DISPLAY_2, PEN_P8, get_buffer_size
from pimoroni_bus import SPIBus

spibus = SPIBus(cs=17, dc=16, sck=18, mosi=19, bl=20)
spibus2 = SPIBus(cs=22, dc=16, sck=18, mosi=19, bl=21)

buffer = bytearray(get_buffer_size(DISPLAY_PICO_DISPLAY_2, PEN_P8))

display = PicoGraphics(display=DISPLAY_PICO_DISPLAY_2, rotate=270, buffer=buffer, bus=spibus, pen_type=PEN_P8)
display2 = PicoGraphics(display=DISPLAY_PICO_DISPLAY_2, rotate= 270, buffer=buffer, bus=spibus2, pen_type=PEN_P8)
```

Note the creating and supplying a buffer step from before, except now we have the `get_buffer_size` helper to give us the right size for a given display/pen type combo.

The latest builds seem fine from my end- totally sure it's not a flaky USB connection?

**Comment by alphanumeric007** [comment]
I had that buffer code in earlier, then took it out thinking I didn't need it. PEN_RGB332 worked just fine without it on my dual display setup, so I left it out.  
 
All my Pico's with the official 1.18.7 connect just fine. And that Pico Lipo connects just fine with 1.18.7. If I put the latest test build on it it just errors when plugged in.
Thonny just reports the following.
Couldn't find the device automatically. 
Check the connection (making sure the device is not in bootloader mode) or choose
"Configure interpreter" in the interpreter menu (bottom-right corner of the window)
to select specific port or another interpreter.

This is on my Windows 10 PC. No issues connecting on my Pi 400 running Pi OS. Same USB Cable.

**Comment by alphanumeric007** [comment]
Looks like I just got lucky on my Pi 400. I did that edit but only got one display, nothing on display 2 with P8. Did a reset and then couldn't connect. Thonny showed that same Couldn't find the device automatically message. 
Could I have messed up my Pico Lipo with all this testing? The official 1.18.7 is fine so I'm thinking it should be OK? 

Another bit of weirdness is if I try to download one of the test uf2 files on my Pi 400, they aren't clickable / downloadable? If I go here on my Pi 400, its just plain text, they don't turn blue when hovered over?
 https://github.com/pimoroni/pimoroni-pico/actions/runs/2496108692

**Comment by Gadgetoid** [comment]
Hmm in both Pico LiPo cases we should have 1024K for binary size, so they're a country mile from exploding themselves- in Pico relative terms at least.

You might need a Pico LiPo sized `flash_nuke.uf2` you can normally take a backup of your whole board beforehand (using picotool: https://github.com/raspberrypi/picotool) if you have any code that's not saved elsewhere.

Perhaps GitHub is spitting broken .uf2 files at you!

**Comment by alphanumeric007** [comment]
Dropped "pimoroni-picolipo_16mb-4f4b88501a92daf32b64808fa0d4055c301cfe41-micropython.uf2" onto it and so far so good. Started and stopped it a few times with no issues. Unplugged it and plugged it back and no error message. My code is running fine with PEN_RGB332 and the buffer code added back in. P8 and P4 won't work with this uf2 though?

**Comment by alphanumeric007** [comment]
Where does one find a 16mb flash nuke file? And does it actually need to be used?

**Comment by Gadgetoid** [comment]
Just added I2C OLED support into MicroPython. Needs some fleshing out, but it works with our 128x128 OLED:

```python
from picographics import PicoGraphics, DISPLAY_I2C_OLED_128X128, PEN_1BIT
from pimoroni_i2c import PimoroniI2C

bus = PimoroniI2C(4, 5)

display = PicoGraphics(DISPLAY_I2C_OLED_128X128, pen_type=PEN_1BIT, bus=bus)

display.set_pen(1)
display.clear()
display.set_font("gothic")
display.set_pen(0)
display.text("Hello World", 0, 10, 0, 0.5)
display.update()
```

This means you can use this little display with all of our boards sporting a Stemma/Qwiic connector.

**Comment by alphanumeric007** [comment]
It looks like what ever Device Descriptor issue I'm having is at my end. 
If I use the SparkFun Cerberus USB Hub Cable, no errors and Thonny connects without issue.
Use a stock straight through cable and I get the error message?
I'd say its either an issue with this PC or with Windows 10?
Tested with a brand new never used before Pi Pico with no headers. 
I'm totally flummoxed by what's going on, but I have a working work around so I'll go with that for now.

**Comment by alphanumeric007** [comment]
Hey Phil, I have a tufty ;) question for you, but have lost that e-mail address you gave me.

**Comment by Gadgetoid** [comment]
> Hey Phil, I have a tufty ;) question for you, but have lost that e-mail address you gave me.

I have a.... tufty answer for you... :eyes:

**Comment by Gadgetoid** [comment]
Merged and released as v1.19.0 - https://github.com/pimoroni/pimoroni-pico/releases/tag/v1.19.0

Open a new issue if you find any other bugs/have any other questions.

Thaannkk yooou to all involved!

**Pull request merged**
