### PR TITLE
Circumvent hangs on update method of inky frame 7 when on battery power

### PR DESCRIPTION
**Pull request by w3stbam**
Some users and myself experienced issues with the update method, which often hangs when the inky frame is powered by batteries.
Discussions:
https://github.com/pimoroni/pimoroni-pico/issues/866
https://forums.pimoroni.com/t/inky-frame-not-refreshing-screen-on-battery-power-using-inky-frame-sleep-for/23174/23

This adds a timeout for the busy_wait function, so that the code continues after a default timeout of 45 seconds. It seems it fixes the issues, as there are no more hangs. Of course, the root cause seems to be somewhere else, but this way we can at least use the update method successfully on battery power.

Relases for testing pruposes can be found here:
https://github.com/w3stbam/pimoroni-pico/releases/

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Thank you! And sorry for missing this before- I'd been embroiled in Pi 5 chaos.

The public API for `busy_wait` should probably not change, so the default value - `=45000` - for `maximum_wait_ms` should probably be in the function declaration (.hpp) and not the definition.

You could probably also leave `is_busy()` as-is, and move the timeout handling to `busy_wait`, since `is_busy()` is in the public API so it could be called without setting a `timeout` value and, I guess, would have unexpected results.

`make_timeout_time_ms` also returns a `absolute_time_t ` (alias of `uint64_t` afaik) rather than an `int`, I think there would be a narrowing conversion and a signedness issue here so something like:

```c++ 
  // hpp
  void busy_wait(uint maximum_wait_ms=45000);
  // cpp
  void Inky73::busy_wait(uint timeout_ms) {
    absolute_time_t  timeout = make_timeout_time_ms(timeout_ms);
    while(is_busy() && !time_reached(timeout)) {
      tight_loop_contents();
    }
  }
```

Note: `time_reached()` looks handy, TIL- https://www.raspberrypi.com/documentation//pico-sdk/hardware.html#ga1e41eca96d5c1b3b5e69e3b1a00cdf7d

These e-ink displays are awkward, I have a timeout-on-busy-wait pattern in most of the Python-equivalent code, so it makes a lot of sense here too. Thank you.

**Comment by stuartleeks** [comment]
Thank you for this. I've been having issues with my Inkyframe hanging on updates but it has been working perfectly since applying the firmware in from your test releases!

I look forward to this being in a official release 😃

**Comment by Gadgetoid** [comment]
Replaced by #900 implementing my suggestions.

I was going to add a `Co-authored-by` but I don't think `f <you@example.com>` is your real email address 😆  so I settled for attribution via the commit message.

Did get a chuckle out of it though.

**Comment by kevinjwalters** [comment]
@Gadgetoid I'm not seeing the mentions on the [release page](https://github.com/pimoroni/pimoroni-pico/releases). What version is this in?

This fix appears to be needed for a 7.3" Inky Frame based on https://forums.pimoroni.com/t/inky-frame-slide-show/19996/35

**Pull request closed without merging**
