### PR TITLE
C++ and MP support and example for LTR559 breakout 

### PR DESCRIPTION
**Pull request by ZodiusInfuser**
Only one example at the moment. May do a PicoExplorer example later today whilst doing trackball.

### CODE REVIEW

**Comment by ZodiusInfuser** [comment]
Okay. A PicoExplorer example isn't getting done today, so maybe just merge this for now?

**Comment by Gadgetoid** [comment]
I'm seeing a much lower proximity output when using this sensor with our C++ driver versus our pure Python one... I'm not sure what accounts for this difference. In both cases the readings are pretty sensible.

Otherwise, everything seems good!

**Comment by ZodiusInfuser** [comment]
Are you meaning the update rate is lower? Because I did add a 100ms time delay to the demos to prevent serial output getting overloaded. Could probably do 50 or 20ms.

**Comment by ZodiusInfuser** [comment]
Spotted some minor issues with my micropython example so pushed an update. For some reason my git lost upstream, so introduced that extra "merge branch" commit.

**Pull request merged**
