### PR TITLE
Add gfx pack carbon intensity bar graph example.

### PR DESCRIPTION
**Pull request by simonprickett**
Adds an additional example showing how to use the UK carbon intensity API and display the information on a GFX pack as a sort of bar graph.

Includes documentation in the code and a small update to the relevant README file.

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Interesting, I had an email from Octopus yesterday saying they'll be doing free hours of energy when green generation peaks. Something they are calling "Power ups." This ties in nicely.

**Comment by simonprickett** [comment]
Just realized there's linting issues here, I'll sort em.

**Comment by simonprickett** [comment]
@Gadgetoid @helgibbons I pushed a commit aimed at solving the linter issues.

**Comment by simonprickett** [comment]
@Gadgetoid played some more linter whackamole here.  Strange thing is pylint in VSCode didn't pick that up.

**Comment by helgibbons** [comment]
Thanks very much for this (and for persevering with the linting!)

There's not a lot of low carbon electricity to be had in Sheffield-on-Sea today...  🌧

**Pull request merged**
