### PR TITLE
Slight refactor of st7789 driver, and addition of the flip function

### PR DESCRIPTION
**Pull request by Pinkyatacme**
As per issue #80, added a flip function. Required minor refactor of code to create a madctl variable for the st7789, as trying to read and update the registers was a miserable failure.

### CODE REVIEW

**Comment by Pinkyatacme** [comment]
Apologies for the 2 borken commits. Note to self - stop working outside the tree!

**Comment by Pinkyatacme** [comment]
Just for completeness, I've retrofitted the portrait mode (pr #75) with the flip screen function.

**Comment by Pinkyatacme** [comment]
Following a comment on the issue note, I've also added the Python updates.

PS. Thanks for the well documented updates to the Micropython repo - made it easy to get the firmware updated and tested :D

**Comment by Gadgetoid** [comment]
As near as I can tell you never set or transfer `madctl[1]`, could `madctl` just be a `uint8_t`?

This goes... weird... on the 240x240 1.3" LCD:

Calling:
```
        screen.init();
        screen.flip();
```

Results in:

image

And unflipped the image is:

image

I think MADCTL can also be set entirely during `init()` by adding some `v_flip`, `h_flip` and (IIRC) `xy_swap` arguments or even just- as per #75- a "rotation" argument.

Yes I'm being awkward by testing this changeset with our 240x240 breakout :laughing:

**Comment by Pinkyatacme** [comment]
Good thinking to test on the 240x240!
The reason for madctl being an array is the command function would also need to be recreated. I did look at what would be needed, and it was a lot more than simply having an array with a redundant element. The way that the MADCTL works is rather odd at first sight, but consistent with what I've seen in other display/graphic controllers - one bit mirrors X, one mirrors Y. I suspect that the base MADCTL is a little off when using 240x240 - back to the datasheet I go! ;-)

**Comment by Gadgetoid** [comment]
Oh just to add fuel to the fire I also have a *round* display here :eyes: 

I decided to collate all the particulars of `MADCTL` into an enum to handle it better:

```patch
diff --git a/drivers/st7789/st7789.hpp b/drivers/st7789/st7789.hpp
index 76bef36..4b352ad 100644
--- a/drivers/st7789/st7789.hpp
+++ b/drivers/st7789/st7789.hpp
@@ -21,7 +21,7 @@ namespace pimoroni {
     int8_t sck    = 18;
     int8_t mosi   = 19;
     int8_t miso   = -1; // we generally don't use this pin
-    int8_t bl     = 20;
+    int8_t bl     = 21;
     int8_t vsync  = -1; // only available on some products
 
     uint32_t spi_baud = 64 * 1024 * 1024;
@@ -41,7 +41,7 @@ namespace pimoroni {
       width(width), height(height),      
       cs(cs), dc(dc), sck(sck), mosi(mosi), miso(miso), frame_buffer(frame_buffer) {}
 
-    void init(bool auto_init_sequence = true);
+    void init(bool auto_init_sequence = true, bool round = false);
 
     void command(uint8_t command, size_t len = 0, const char *data = NULL);
     void vsync_callback(gpio_irq_callback_t callback);
@@ -49,6 +49,20 @@ namespace pimoroni {
     void set_backlight(uint8_t brightness);
     void flip();
 
+    enum MADCTL : uint8_t {
+      ROW_ORDER   = 0b10000000,
+      COL_ORDER   = 0b01000000,
+      SWAP_XY     = 0b00100000,  // AKA "MV"
+      SCAN_ORDER  = 0b00010000,
+      RGB         = 0b00001000,
+      HORIZ_ORDER = 0b00000100
+    };
+
+    #define ROT_240_240_0      0
+    #define ROT_240_240_90     MADCTL::SWAP_XY | MADCTL::HORIZ_ORDER | MADCTL::COL_ORDER
+    #define ROT_240_240_180    MADCTL::SCAN_ORDER | MADCTL::HORIZ_ORDER | MADCTL::COL_ORDER | MADCTL::ROW_ORDER
+    #define ROT_240_240_270    MADCTL::SWAP_XY | MADCTL::HORIZ_ORDER | MADCTL::ROW_ORDER
+
     enum reg {
       SWRESET   = 0x01,
       TEON      = 0x35,

```

And then store as `uint8_t` and handle conversion to `char *` when it's transmitted:

```
diff --git a/drivers/st7789/st7789.cpp b/drivers/st7789/st7789.cpp
index 0c1c567..705641f 100644
--- a/drivers/st7789/st7789.cpp
+++ b/drivers/st7789/st7789.cpp
@@ -7,9 +7,11 @@
 #include "hardware/pwm.h"
 
 namespace pimoroni {
-  char madctl[2];
+  uint8_t madctl;
+  uint16_t caset[2] = {0, 0};
+  uint16_t raset[2] = {0, 0};
 
-  void ST7789::init(bool auto_init_sequence) {
+  void ST7789::init(bool auto_init_sequence, bool round) {
     // configure spi interface and pins
     spi_init(spi, spi_baud);
 
@@ -50,19 +52,6 @@ namespace pimoroni {
 
       sleep_ms(150);
 
-      if(width == 240 && height == 240) {
-        madctl[0] = 0x04;
-      }
-
-      if(width == 240 && height == 135) {
-        madctl[0] = 0x70;
-      }
-      
-      if(width == 135 && height == 240) {
-               madctl[0] = 0x00;
-      }
-
-      command(reg::MADCTL,    1, madctl);  // row/column addressing order - rgb pixel order
       command(reg::TEON,      1, "\x00");  // enable frame sync signal if used
       command(reg::COLMOD,    1, "\x05");  // 16 bits per pixel
 
@@ -74,19 +63,38 @@ namespace pimoroni {
 
       // setup correct addressing window
       if(width == 240 && height == 240) {
-        command(reg::CASET,     4, "\x00\x00\x00\xef");  // 0 .. 239 columns
-        command(reg::RASET,     4, "\x00\x00\x00\xef");  // 0 .. 239 rows
+        caset[0] = 0;
+        caset[1] = 239;
+        raset[0] = round ? 40 : 0;
+        raset[1] = round ? 279 : 239;
+        madctl = MADCTL::HORIZ_ORDER;
       }
 
       if(width == 240 && height == 135) {
-        command(reg::RASET,     4, "\x00\x35\x00\xbb"); // 53 .. 187 (135 rows)
-        command(reg::CASET,     4, "\x00\x28\x01\x17"); // 40 .. 279 (240 columns)
+        caset[0] = 40;   // 240 cols
+        caset[1] = 279;
+        raset[0] = 53;   // 135 rows
+        raset[1] = 187;
+        madctl = MADCTL::COL_ORDER | MADCTL::SWAP_XY | MADCTL::SCAN_ORDER;
       }
 
       if(width == 135 && height == 240) {
-        command(reg::CASET,     4, "\x00\x34\x00\xba"); // 52 .. 186 (135 rows)
-        command(reg::RASET,     4, "\x00\x28\x01\x17"); // 40 .. 279 (240 columns)
+        caset[0] = 52;   // 135 cols
+        caset[1] = 186;
+        raset[0] = 40;   // 240 rows
+        raset[1] = 279;
+        madctl = 0;
       }
+
+      // Byte swap the 16bit rows/cols values
+      caset[0] = __builtin_bswap16(caset[0]);
+      caset[1] = __builtin_bswap16(caset[1]);
+      raset[0] = __builtin_bswap16(raset[0]);
+      raset[1] = __builtin_bswap16(raset[1]);
+
+      command(reg::CASET,     4, (char *)caset);
+      command(reg::RASET,     4, (char *)raset);
+      command(reg::MADCTL,    1, (char *)&madctl);
     }
 
     // the dma transfer works but without vsync it's not that useful as you could
@@ -160,7 +168,7 @@ namespace pimoroni {
   }
 
   void ST7789::flip(){
-    madctl[0] ^= 0xC0;
-    command(reg::MADCTL,    1, madctl);
+    madctl ^= MADCTL::ROW_ORDER | MADCTL::COL_ORDER;
+    command(reg::MADCTL,    1, (char *)&madctl);
   }
 }
 ```
 
Note also that I've done the same with `CASET` and `RASET`, storing them as `uint16_t` because that is- after all- what the values are. These are then byteswapped and converted to `char *` when sent. It takes me hours to wrap my head around this stuff every time I do it... but the payoff in code clarity is huge.

Also my rotation settings don't quite work- I think some rotations require a memory offset, just for fun.

**Comment by Gadgetoid** [comment]
Above changes are in this commit which you can grab as a patch - https://github.com/pimoroni/pimoroni-pico/commit/55bd4dd02fc67a702811da1ac88021f5b69713e9?branch=55bd4dd02fc67a702811da1ac88021f5b69713e9&diff=unified

If you want to play with it, you can apply it like so:

```
wget https://github.com/pimoroni/pimoroni-pico/commit/55bd4dd02fc67a702811da1ac88021f5b69713e9.patch
git am 55bd4dd02fc67a702811da1ac88021f5b69713e9.patch
```

Just need to figure out all the possible rotation combinations of these registers now :grimacing:

**Comment by Gadgetoid** [comment]
Switching to #103 to finish this off (merging #103 should, in theory, flag this PR as merged anyway).

**Pull request closed without merging**
