### PR TITLE
Update examples to use PicoGraphics

### LINKED ISSUE #393: Pico Display module is missing
Would love to see what is available for use, vs. what's in the examples.

### LINKED ISSUE #408: Tufty 2040 Name Badge - Instruction gives wrong name for text file
In the tufty 2040 example name_badge.py line 25 "name = "open name.txt in thonny to edit badge :)"" says the user should be making a name.txt file but the file thats loaded in line 21 "file = open("badge.txt", "r")" refers to badge.txt

Either line 21 is changed to name.txt 

or

Line 25 is changed to badge.txt

### LINKED ISSUE #423: Demo Examples  no module s7789
I just had a go at running the examples following the pico explorer breakout.
Hello world works, so pico works.
Copied across custom uf2 (1.19) https://github.com/pimoroni/pimoroni-pico/releases/tag/v1.19.0

In Thonny (3.3.13) with MicroPython (RPi Pico) selceted
Ran the demo example updated 19 days ago https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/examples/pico_explorer
 and it's complaining 
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ImportError: no module named 'st7789'
```

### PR DESCRIPTION
**Pull request by helgibbons**
All MicroPython examples for Pico Display, Pico Explorer and the LCD breakouts are now updated to use PicoGraphics. They should now work properly with v1.19 and later (I had a general tidy up as well and renamed some examples to be more consistent).

Fixes #423 and fixes #393 .

I also fixed #408 in passing :)

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Wowser, you *have* been busy! Thank you.

**Comment by Gadgetoid** [comment]
Thank you, ran an eyeball test on these and tried a couple locally. Great stuff.

**Comment by socratesv** [comment]
Hello all, has anyone tried to use a third party ST7789 display such as the SPI DFRobot 2.0: 320x240 IPS display?  I can get it to work with an old ST7789 driver but only in 240x240 mode (even though the driver supports 320x240) and no luck using picographics with any of the recent releases....

Looking forward to any insights !!!

By the way - you are all fantastic and keep up this excellent work !!!

Many thanks

**Comment by Gadgetoid** [comment]
> DFRobot 2.0: 320x240

Looks like it's actually 240x320 which explains why it wont work with PicoGraphics, although if you use "DISPLAY_PICO_DISPLAY_2" it should at least do *something*.

**Pull request merged**
