### PR TITLE
Add Pico Display Pack 2.8 and fix SPI for st7789 on Pico2

### PR DESCRIPTION
**Pull request by peardox**
This adds libraries/pico_display_28 along with a demo that displays the FPS in examples/pico_display_28

Also updated drivers/st7789 as per #985 / #1005

Full repo build impossible owing to hardware/rtc.h not existing for Pico2 when it hits breakout_encoder_wheel (about to raise issue) so just built and tested pico_display_28

### CODE REVIEW

**Comment by Slion** [comment]
Why do we need a specifix example for 2.8? I thought is was exactly the same as the 2 but physically larger.

**Comment by peardox** [comment]
> Why do we need a specific example for 2.8? I thought is was exactly the same as the 2 but physically larger.

It is't a carbon copy. It changes the text from "Hello World" to one that displays the Frames Per Second which is calculated on every update so has a benefit not present in other demos (as none of them do FPS)

**Comment by Slion** [comment]
> The baud rate is dependant on the device in modified driver/st7789.hpp

Yeah I saw that I was just wondering if the faster baud rate also works on Pico 1.

**Comment by peardox** [comment]
> Yeah I saw that I was just wondering if the faster baud rate also works on Pico 1.

I most sincerely doubt it (might give it a go tho)

The baud rate is tied to the system clock and those values are 1/2 device clock frequency (Pico 1 should be 66.5 for 1/2 freq - might be worth a try) although the docs say 16us apparently

**Comment by Gadgetoid** [comment]
Sorry, it's been a busy time and I haven't got 'round to testing this yet 😬 

Nonetheless, this is appreciated thank you!

**Comment by Slion** [comment]
In fact you really need that header defining the RGB pins cause they were changed for that display.

**Comment by Gadgetoid** [comment]
Thank you!

**Pull request merged**
